language: python

stages:
  - linter
  - test

python:
  - 3.5
  - 3.6

env:
  - DJANGO_SETTINGS_MODULE=etip.settings.dev

install:
  - pip install -r requirements.txt

script:
  - cd etip/
  - python manage.py test

jobs:
  include:
    - stage: linter
      python: 3.6
      install:
        - pip install flake8
      script:
        - flake8 etip/
