language: python

stages:
  - linter
  - test

env:
  - DJANGO_SETTINGS_MODULE=etip.settings.dev

jobs:
  include:
    - stage: linter
      python:
        - 3.5
      install:
        - pip install flake8
      script:
        - flake8 etip/
    - stage: test
      python:
        - 3.5
        - 3.6
      install:
        - pip install -r requirements.txt
      script:
        - cd etip/
        - python manage.py test
