# Generated by Django 2.0.3 on 2018-04-01 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('code_signature', models.CharField(default='', max_length=500)),
                ('network_signature', models.CharField(default='', max_length=500)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trackers.Category')),
            ],
            bases=('trackers.category',),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trackers.Category')),
            ],
            bases=('trackers.category',),
        ),
        migrations.CreateModel(
            name='Capabilities',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trackers.Category')),
            ],
            bases=('trackers.category',),
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trackers.Category')),
            ],
            bases=('trackers.category',),
        ),
        migrations.AddField(
            model_name='tracker',
            name='advertising',
            field=models.ManyToManyField(to='trackers.Advertising'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='analytics',
            field=models.ManyToManyField(to='trackers.Analytics'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='capabilities',
            field=models.ManyToManyField(to='trackers.Capabilities'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='networks',
            field=models.ManyToManyField(to='trackers.Networks'),
        ),
    ]
