# Generated by Django 2.0.3 on 2018-04-01 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('trackers', '0001_initial'), ('trackers', '0002_auto_20180401_1312'), ('trackers', '0003_auto_20180401_1312'), ('trackers', '0004_auto_20180401_1313'), ('trackers', '0005_auto_20180401_1314'), ('trackers', '0006_auto_20180401_1342'), ('trackers', '0007_auto_20180401_1401'), ('trackers', '0008_auto_20180401_1606')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('code_signature', models.CharField(default='', max_length=500)),
                ('network_signature', models.CharField(default='', max_length=500)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trackers.Category')),
            ],
            bases=('trackers.category',),
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trackers.Category')),
            ],
            bases=('trackers.category',),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trackers.Category')),
            ],
            bases=('trackers.category',),
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trackers.Category')),
            ],
            bases=('trackers.category',),
        ),
        migrations.AddField(
            model_name='tracker',
            name='advertising',
            field=models.ManyToManyField(blank=True, to='trackers.Advertising'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='analytic',
            field=models.ManyToManyField(blank=True, to='trackers.Analytic'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='capability',
            field=models.ManyToManyField(blank=True, to='trackers.Capability'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='network',
            field=models.ManyToManyField(blank=True, to='trackers.Network'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='code_signature',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='network_signature',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='is_in_exodus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracker',
            name='is_in_exodus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracker',
            name='artifact_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='gradle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='maven_repository',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
