# Generated by Django 2.2.12 on 2020-04-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_auto_20190508_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='api_key_ids',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
