# Generated by Django 2.2.12 on 2020-05-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_tracker_api_key_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
