# Generated by Django 2.2.15 on 2020-08-31 18:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackers', '0005_trackerapproval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackerapproval',
            unique_together={('tracker', 'approver')},
        ),
    ]
