# Generated by Django 2.2.17 on 2021-05-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0006_auto_20200831_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='exodus_matches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
