# Generated by Django 2.2.17 on 2021-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0006_auto_20200831_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='documentation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
