# Generated by Django 2.2.17 on 2021-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0007_tracker_exodus_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='documentation',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
