# Generated by Django 2.2.27 on 2022-02-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0008_tracker_exodus_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='needs_rework',
            field=models.BooleanField(default=False),
        ),
    ]
