---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev --system
      - name: Lint with flake8
        run: |
          flake8 etip/
      - name: Check if lock is uptodate
        run: |
          pipenv install --deploy
      - name: Check vulnerabilites in dependencies
        run: |
          pipenv check
      - name: Run Tests
        run: |
          cd etip
          python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: etip.settings.dev
  release:
    needs: build
    name: Create Github release
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create release
        run: gh release create ${GITHUB_REF_NAME} --title ${GITHUB_REF_NAME} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
